-- Fas 3 — seeda default-mallar (idempotent, hoppar över om namn+category redan finns)

INSERT INTO "contract_templates" ("name", "category", "own_company_id", "content", "variables", "version", "created_at", "updated_at")
SELECT
  'Anställningsavtal — Tillsvidare',
  'TILLSVIDAREANSTALLNING',
  (SELECT id FROM own_companies ORDER BY id LIMIT 1),
  E'<h1 style="text-align:center">ANSTÄLLNINGSAVTAL</h1>\n<p style="text-align:center">Tillsvidareanställning</p>\n<hr/>\n<h2>Parter</h2>\n<p><strong>Arbetsgivare:</strong> {{company.name}}, org.nr {{company.organizationNumber}}<br/>Adress: {{company.address}}</p>\n<p><strong>Arbetstagare:</strong> {{employee.firstName}} {{employee.lastName}}, personnummer {{employee.personalNumber}}<br/>Adress: {{employee.address}}</p>\n<h2>Anställningsvillkor</h2>\n<p><strong>Befattning:</strong> {{employment.role}}<br/><strong>Anställningsform:</strong> Tillsvidareanställning<br/><strong>Anställningsgrad:</strong> {{employment.occupationPct}} %<br/><strong>Tillträdesdag:</strong> {{employment.startDate}}<br/><strong>Arbetsplats:</strong> {{employment.workplace}}<br/><strong>Arbetstid:</strong> {{employment.workHours}}</p>\n<h2>Lön och förmåner</h2>\n<p><strong>Månadslön:</strong> {{employment.salary}} kr<br/><strong>Semester:</strong> {{employment.vacation}}<br/><strong>Kollektivavtal:</strong> {{employment.collectiveAgreement}}</p>\n<h2>Uppsägning</h2>\n<p><strong>Uppsägningstid:</strong> {{employment.noticePeriod}}</p>\n<h2>Övriga villkor</h2>\n<p>{{employment.otherTerms}}</p>\n<h2>Signaturer</h2>\n<p>{{company.name}}<br/>Datum: {{today}}<br/><br/>_______________________________<br/>{{company.signatoryName}}</p>\n<br/><p>{{employee.firstName}} {{employee.lastName}}<br/>Datum: {{today}}<br/><br/>_______________________________</p>',
  '{"required":["employee.firstName","employee.lastName","employee.personalNumber","employment.role","employment.startDate","employment.salary","employment.occupationPct"]}'::jsonb,
  1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM contract_templates WHERE name = 'Anställningsavtal — Tillsvidare');

INSERT INTO "contract_templates" ("name", "category", "own_company_id", "content", "variables", "version", "created_at", "updated_at")
SELECT
  'Provanställning (6 mån)',
  'PROVANSTALLNING',
  (SELECT id FROM own_companies ORDER BY id LIMIT 1),
  E'<h1 style="text-align:center">ANSTÄLLNINGSAVTAL</h1>\n<p style="text-align:center">Provanställning</p>\n<hr/>\n<h2>Parter</h2>\n<p><strong>Arbetsgivare:</strong> {{company.name}}, org.nr {{company.organizationNumber}}<br/>Adress: {{company.address}}</p>\n<p><strong>Arbetstagare:</strong> {{employee.firstName}} {{employee.lastName}}, personnummer {{employee.personalNumber}}<br/>Adress: {{employee.address}}</p>\n<h2>Anställningsvillkor</h2>\n<p><strong>Befattning:</strong> {{employment.role}}<br/><strong>Anställningsform:</strong> Provanställning enligt LAS § 6<br/><strong>Provanställning till och med:</strong> {{employment.probationEndDate}}<br/><strong>Anställningsgrad:</strong> {{employment.occupationPct}} %<br/><strong>Tillträdesdag:</strong> {{employment.startDate}}<br/><strong>Arbetsplats:</strong> {{employment.workplace}}<br/><strong>Arbetstid:</strong> {{employment.workHours}}</p>\n<p>Efter provanställningens utgång övergår anställningen automatiskt i tillsvidareanställning under förutsättning att arbetsgivaren inte skriftligen meddelat annat senast två veckor före provanställningens utgång.</p>\n<h2>Lön och förmåner</h2>\n<p><strong>Månadslön:</strong> {{employment.salary}} kr<br/><strong>Semester:</strong> {{employment.vacation}}<br/><strong>Kollektivavtal:</strong> {{employment.collectiveAgreement}}</p>\n<h2>Uppsägning under provanställning</h2>\n<p>Såväl arbetsgivare som arbetstagare kan avbryta provanställningen med två veckors varsel utan angivande av skäl.</p>\n<h2>Signaturer</h2>\n<p>{{company.name}}<br/>Datum: {{today}}<br/><br/>_______________________________<br/>{{company.signatoryName}}</p>\n<br/><p>{{employee.firstName}} {{employee.lastName}}<br/>Datum: {{today}}<br/><br/>_______________________________</p>',
  '{"required":["employee.firstName","employee.lastName","employee.personalNumber","employment.role","employment.startDate","employment.probationEndDate","employment.salary","employment.occupationPct"]}'::jsonb,
  1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM contract_templates WHERE name = 'Provanställning (6 mån)');

INSERT INTO "contract_templates" ("name", "category", "own_company_id", "content", "variables", "version", "created_at", "updated_at")
SELECT
  'Visstidsanställning',
  'VISSTIDSANSTALLNING',
  (SELECT id FROM own_companies ORDER BY id LIMIT 1),
  E'<h1 style="text-align:center">ANSTÄLLNINGSAVTAL</h1>\n<p style="text-align:center">Visstidsanställning</p>\n<hr/>\n<h2>Parter</h2>\n<p><strong>Arbetsgivare:</strong> {{company.name}}, org.nr {{company.organizationNumber}}<br/>Adress: {{company.address}}</p>\n<p><strong>Arbetstagare:</strong> {{employee.firstName}} {{employee.lastName}}, personnummer {{employee.personalNumber}}<br/>Adress: {{employee.address}}</p>\n<h2>Anställningsvillkor</h2>\n<p><strong>Befattning:</strong> {{employment.role}}<br/><strong>Anställningsform:</strong> Visstidsanställning (allmän visstidsanställning)<br/><strong>Tillträdesdag:</strong> {{employment.startDate}}<br/><strong>Slutdatum:</strong> {{employment.endDate}}<br/><strong>Anställningsgrad:</strong> {{employment.occupationPct}} %<br/><strong>Arbetsplats:</strong> {{employment.workplace}}<br/><strong>Arbetstid:</strong> {{employment.workHours}}</p>\n<h2>Lön och förmåner</h2>\n<p><strong>Månadslön:</strong> {{employment.salary}} kr<br/><strong>Semester:</strong> {{employment.vacation}}<br/><strong>Kollektivavtal:</strong> {{employment.collectiveAgreement}}</p>\n<h2>Anställningens upphörande</h2>\n<p>Anställningen upphör utan uppsägning vid ovan angivet slutdatum.</p>\n<h2>Signaturer</h2>\n<p>{{company.name}}<br/>Datum: {{today}}<br/><br/>_______________________________<br/>{{company.signatoryName}}</p>\n<br/><p>{{employee.firstName}} {{employee.lastName}}<br/>Datum: {{today}}<br/><br/>_______________________________</p>',
  '{"required":["employee.firstName","employee.lastName","employee.personalNumber","employment.role","employment.startDate","employment.endDate","employment.salary","employment.occupationPct"]}'::jsonb,
  1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM contract_templates WHERE name = 'Visstidsanställning');

INSERT INTO "contract_templates" ("name", "category", "own_company_id", "content", "variables", "version", "created_at", "updated_at")
SELECT
  'Timanställning',
  'TIMANSTALLNING',
  (SELECT id FROM own_companies ORDER BY id LIMIT 1),
  E'<h1 style="text-align:center">ANSTÄLLNINGSAVTAL</h1>\n<p style="text-align:center">Timanställning</p>\n<hr/>\n<h2>Parter</h2>\n<p><strong>Arbetsgivare:</strong> {{company.name}}, org.nr {{company.organizationNumber}}</p>\n<p><strong>Arbetstagare:</strong> {{employee.firstName}} {{employee.lastName}}, personnummer {{employee.personalNumber}}<br/>Adress: {{employee.address}}</p>\n<h2>Anställningsvillkor</h2>\n<p><strong>Befattning:</strong> {{employment.role}}<br/><strong>Anställningsform:</strong> Timanställning (intermittent)<br/><strong>Tillträdesdag:</strong> {{employment.startDate}}<br/><strong>Arbetsplats:</strong> {{employment.workplace}}</p>\n<p>Arbete utförs efter överenskommelse i varje enskilt fall. Arbetstagaren är inte skyldig att stå till förfogande utanför överenskomna arbetstillfällen.</p>\n<h2>Lön</h2>\n<p><strong>Timlön:</strong> {{employment.hourlyRate}} kr/tim<br/><strong>Semester och OB:</strong> Semesterersättning 12 % och OB-tillägg utgår enligt kollektivavtal.<br/><strong>Kollektivavtal:</strong> {{employment.collectiveAgreement}}</p>\n<h2>Signaturer</h2>\n<p>{{company.name}}<br/>Datum: {{today}}<br/><br/>_______________________________<br/>{{company.signatoryName}}</p>\n<br/><p>{{employee.firstName}} {{employee.lastName}}<br/>Datum: {{today}}<br/><br/>_______________________________</p>',
  '{"required":["employee.firstName","employee.lastName","employee.personalNumber","employment.role","employment.startDate","employment.hourlyRate"]}'::jsonb,
  1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM contract_templates WHERE name = 'Timanställning');
